name: chain

on:
  workflow_dispatch:
    inputs:
      hub_1:
        description: 'Test description'
        required: true
        type: string
      hub_2:
        description: 'Test description'
        required: true
        type: string

jobs:
  deploy_hub_1:
    runs-on: ubuntu-20.04
    if: ${{ github.event.inputs.hub_1 == 'true' }}

    steps:
      - name: hub_1 deployed
        run: |
          echo hub_1 is deployed
  
  deploy_hub_2:
    runs-on: ubuntu-20.04
    needs: deploy_hub_1
    if: ${{ github.event.inputs.hub_2 == 'true' }}

    steps:
      - name: hub_2 deployed
        run: |
          echo hub_2 is deployed
