# This workflow is dispatched by the "chain dispatcher" workflow and is expected
# to run in parallel a lot.
#
name: chain

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'The cluster to deploy hubs to'
        required: true
        type: string
      hub_1:
        description: 'The first hub to deploy'
        required: true
        type: string
      hub_2:
        description: 'The second (optional) hub to deploy'
        required: true
        default: ""
        type: string
      # concurrency:
      #   description: 'A identifier to ensure we don't deploy the same hub combination'
      #   required: true
      #   type: string

jobs:
  # TODO: Add sensible "concurrency" to ensure we don't deploy the same hub
  #       concurrently if we happen to dispatch this workflow many times for
  #       some reason. We may need to have that concurrency as workflow input.
  #
  deploy-up-to-two-hubs-in-sequence:
    runs-on: ubuntu-20.04
    name: "Deploy to ${{ github.event.inputs.cluster }}: ${{ github.event.inputs.hub_1 }} ${{ github.event.inputs.hub_2 }}"
    # concurrency: ${{ github.event.inputs.concurrency }}

    steps:
      - name: "Deploy: ${{ github.event.inputs.cluster }}/${{ github.event.inputs.hub_1 }}"
        run: echo

      - name: "Deploy: ${{ github.event.inputs.cluster }}/${{ github.event.inputs.hub_2 }}"
        if: ${{ github.event.inputs.hub_2 != '' }}
        run: echo
