name: chain

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'The cluster to deploy hubs to'
        required: true
        type: string
      hub_1:
        description: 'The first hub to deploy'
        required: true
        type: string
      hub_2:
        description: 'The second (optional) hub to deploy'
        required: true
        default: ""
        type: string

jobs:
  job_1:
    runs-on: ubuntu-20.04
    name: Deploy hub ${{ github.event.inputs.hub_2 }} to cluster ${{ github.event.inputs.cluster }}

    steps:
      - name: Deploy hub ${{ github.event.inputs.hub_2 }} to cluster ${{ github.event.inputs.cluster }}
        run: |
          echo Deploying hub ${{ github.event.inputs.hub_2 }} to cluster ${{ github.event.inputs.cluster }}...
  
  job_2:
    runs-on: ubuntu-20.04
    name: Deploy hub ${{ github.event.inputs.hub_2 }} to cluster ${{ github.event.inputs.cluster }}
    
    needs: job_1
    if: ${{ github.event.inputs.hub_2 != '' }}

    steps:
      - name: Deploy hub ${{ github.event.inputs.hub_2 }} to cluster ${{ github.event.inputs.cluster }}
        run: |
          echo Deploying hub ${{ github.event.inputs.hub_2 }} to cluster ${{ github.event.inputs.cluster }}...
