name: chain dispatcher

on:
  workflow_dispatch:

jobs:
  initial-job:
    runs-on: ubuntu-20.04
    steps:
      # list workflows
      # https://docs.github.com/en/rest/reference/actions#list-repository-workflows
      - run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows
      # create a workflow dispatch event
      # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event
      - env:
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
        run: |
          curl \
            -X POST \
            -H "Authorization: token $WORKFLOW_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/21985128/dispatches \
            -d '{"ref":"main","inputs":{"cluster":"eriks_cluster","eriks_staging_hub":"true","eriks_prod_hub":"true"}}'

          curl \
            -X POST \
            -H "Authorization: token $WORKFLOW_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/21985128/dispatches \
            -d '{"ref":"main","inputs":{"cluster":"sarahs_cluster","hub_1":"sarahs_staging_hub","hub_2":"sarahs_prod_hub"}}'
